version: "3"

services:
  postgres:
    container_name: postgresql_test
    build: ./database
    ports:
     - "5432:5432"
    volumes:
      - postgres-store:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    restart: always

volumes:
  postgres-store: